general.import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[window.padding]
x = 5

[window]
decorations = "full" # Garante que o Alacritty aceite as decorações do sistema
